#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 31 14:02:33 2019

@author: adam
"""


# import os
import pathlib
# import datetime
# import time
# import warnings
# from typing import Tuple, Any

# import numpy as np
# import pims
import pandas as pd
# from nd2reader import ND2Reader
# # from scipy import stats
# from scipy import spatial
import yaml

# import gspread
# from oauth2client.service_account import ServiceAccountCredentials

import trackpy as tp

analyzed_data_location = pathlib.Path(
                '/Users/adam/Documents/SenseOfTouchResearch/'
                'SSN_ImageAnalysis/AnalyzedData/' + 'SSN_116_001' + '/')

unlinked_particles_path = analyzed_data_location.joinpath(
                'unlinkedTrackpyBatchResults.yaml')


with open(unlinked_particles_path, 'r') as yamlfile:
    unlinked_mitos_dict = yaml.load(yamlfile)
    mitos_from_batch = pd.DataFrame.from_dict(
            unlinked_mitos_dict, orient='index')

linked = tp.link_df(mitos_from_batch,
                    25,
                    pos_columns=['x', 'y', 'z'])

linked_mitos = tp.filter_stubs(linked, 7)
